name: rebase-pull-request

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      pull-request:
        default: "stale"
        description: |
          pull request to rebase
      base-branch:
        default: "main"
        description: |
          pull request to rebase

jobs:
  rebase-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write # update branches used by pull requests
      pull-requests: write # update pull request base branch
    steps:
      - uses: oliverlee/rebase-pull-request@v0
        with:
          checkout-ssh-key: ${{ secrets.PR_UPDATE_DEPLOY_KEY }}
          pull-request: ${{ github.event.inputs.pull-request || 'stale' }}
          base-branch: ${{ github.event.inputs.base-branch || 'main' }}
